# Generated by Django 5.0.2 on 2024-03-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
