# Generated by Django 5.0.2 on 2024-04-17 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_grouppost_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='nb_follow',
        ),
    ]
