# Generated by Django 5.0.2 on 2024-04-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_grouppost_approval_date_alter_grouppost_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='approval_date',
            field=models.DateTimeField(null=True),
        ),
    ]
