# Generated by Django 5.0.2 on 2024-04-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_grouppost_approval_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='approval_date',
            field=models.DateTimeField(blank=True, default='2024-01-01'),
            preserve_default=False,
        ),
    ]
