# Generated by Django 5.0.6 on 2024-05-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_birthday_user_gender_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_couv',
            field=models.FileField(null=True, upload_to='coverPic'),
        ),
    ]
