# Generated by Django 5.0.2 on 2024-05-08 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_alter_grouppost_approval_date'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reported_post',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='groups.grouppost'),
            preserve_default=False,
        ),
    ]
